# Лабораторная работа 9. Использование разработанного пайплайна для многомерной регрессии

## Подключение библиотек

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Загрузка данных и разделение на матрицу признаков и зависимую переменную

In [3]:
dataset = pd.read_csv('Indian startups funding in 2021.csv')
dataset.head()

Company/Brand  Founded Headquarters                            Sector  \
0  CollegeDekho   2015.0      Gurgaon                        E-learning   
1          BOX8   2012.0       Mumbai                  Food & Beverages   
2         Simpl   2015.0    Bangalore                 Consumer Services   
3   8i Ventures   2018.0       Mumbai  Venture Capital & Private Equity   
4     PayGlocal   2021.0    Bangalore                Financial Services   

                                        What it does  \
0  Collegedekho.com is Student’s Partner, Friend ...   
1                   India's Largest Desi Meals Brand   
2  Simpl empowers merchants to build trusted rela...   
3  8i is a Mumbai & Bangalore based early stage f...   
4  PayGlocal is a FinTech solving for global paym...   

                                        Founder/s  \
0                                    Ruchir Arora   
1                          Anshul Gupta, Amit Raj   
2                        Nitya, Chaitra Chidanand   
3                                  Vikram Chachra   
4  Prachi Dharani, Rohit Sukhija, Yogesh Lokhande   

                    Investor/s Amount(in dollars)     Stage  Month  
0             Disrupt ADQ, QIC           35000000  Series B     12  
1                 Tiger Global           40000000       NaN     12  
2  Valar Ventures, IA Ventures           40000000  Series B     12  
3                          NaN           50000000       NaN     12  
4        Sequoia Capital India            4900000  Series A     12

In [41]:
X = dataset.iloc[:, [9]].values
y = dataset.iloc[:, [1]].values
print ("Матрица признаков"); print(X[:10])
print ("Зависимая переменная"); print(y[:10])

Матрица признаков
[[12]
 [12]
 [12]
 [12]
 [12]
 [12]
 [12]
 [12]
 [12]
 [12]]
Зависимая переменная
[[2015.]
 [2012.]
 [2015.]
 [2018.]
 [2021.]
 [2016.]
 [2018.]
 [2018.]
 [2017.]
 [2015.]]


### Применение OneHotEncoder

In [42]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import make_column_transformer
labelencoder = LabelEncoder()
X[:, 0] = labelencoder.fit_transform(X[:, 0])
onehotencoder = make_column_transformer((OneHotEncoder(), [0]),remainder='passthrough')
X = onehotencoder.fit_transform(X[:, [0]]).toarray()
print("Перекодировка категориального признака")
print(X[:4,:])

Перекодировка категориального признака
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


## Для предотвращения мультиколлениврности необходимо избавиться от одной из фиктивных переменных, добавленных в результате обработки категориальных признаков

In [43]:
X = X[:, 1:]
print(X[:6,:])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


## Разделение выборки на тестовую и тренировочную

In [44]:
# from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Обучение линейной модели регрессии

In [45]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

### Обработка результатов, тюнинг модели

#### Предсказание

In [46]:
y_pred = regressor.predict(X_test)
print(y_pred)

[[2016.8877551 ]
 [2014.578125  ]
 [2014.578125  ]
 [2015.91549296]
 [2017.14736842]
 [2016.95522388]
 [2016.32307692]
 [2015.86138614]
 [2017.03125   ]
 [2017.26530612]
 [2014.578125  ]
 [2017.03125   ]
 [2016.95522388]
 [2016.59615385]
 [2017.26530612]
 [2017.16964286]
 [2017.36752137]
 [2015.91549296]
 [2015.91549296]
 [2015.91549296]
 [2017.16964286]
 [2016.32307692]
 [2016.32307692]
 [2017.14736842]
 [2016.59615385]
 [2016.32307692]
 [2017.16964286]
 [2017.14736842]
 [2016.59615385]
 [2015.86138614]
 [2015.86138614]
 [2017.16964286]
 [2017.14736842]
 [2016.32307692]
 [2016.8877551 ]
 [2016.95522388]
 [2017.36752137]
 [2015.86138614]
 [2016.95522388]
 [2014.578125  ]
 [2017.14736842]
 [2017.14736842]
 [2017.03125   ]
 [2014.578125  ]
 [2016.59615385]
 [2015.91549296]
 [2016.32307692]
 [2017.16964286]
 [2016.32307692]
 [2017.16964286]
 [2016.8877551 ]
 [2016.8877551 ]
 [2016.32307692]
 [2016.95522388]
 [2015.86138614]
 [2017.14736842]
 [2016.8877551 ]
 [2014.578125  ]
 [2017.3675213

#### Оптимизация модели

In [65]:
import statsmodels.formula.api as sm
# Предположим, что X и y уже определены и содержат данные

# Проверка размера X и y
print("Размер X:", X.shape)
print("Размер y:", y.shape)


# Добавление столбца единиц
X = np.append(arr = np.ones((X.shape[0], 1)).astype(int), values = X, axis = 1)
X_opt = X[:, [1]]
model = sm.ols(formula='y ~ X + y', data=dataset)
results = model.fit()
results.summary()

Размер X: (1194, 28)
Размер y: (1194, 1)


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 1.055e+25
Date:                Tue, 01 Apr 2025   Prob (F-statistic):               0.00
Time:                        19:39:08   Log-Likelihood:                 28140.
No. Observations:                1193   AIC:                        -5.625e+04
Df Residuals:                    1180   BIC:                        -5.619e+04
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -2.101e-12   9.58e-12     -0.219      0.826   -2.09e-11    1.67e-11
X[0]       -2.264e-12   9.58e-12     -0.236      0.813   -2.11e-11    1.65e-11
X[1]       -1.333e-12   9.58e-12     -0.139      0.889   -2.01e-11    1.75e-11
X[2]       -2.939e-12   9.58e-12     -0.307      0.759   -2.17e-11    1.59e-11
X[3]       -1.044e-12   9.58e-12     -0.109      0.913   -1.98e-11    1.78e-11
X[4]       -2.465e-12   9.58e-12     -0.257      0.797   -2.13e-11    1.63e-11
X[5]       -2.218e-12   9.58e-12     -0.232      0.817    -2.1e-11    1.66e-11
X[6]       -1.053e-12   9.58e-12     -0.110      0.913   -1.99e-11    1.77e-11
X[7]       -1.895e-12   9.58e-12     -0.198      0.843   -2.07e-11    1.69e-11
X[8]       -1.159e-12   9.58e-12     -0.121      0.904      -2e-11    1.76e-11
X[9]       -2.069e-12   9.58e-12     -0.216      0.829   -2.09e-11    1.67e-11
X[10]      -2.666e-12   9.58e-12     -0.278      0.781   -2.15e-11    1.61e-11
X[11]       -2.41e-12   9.58e-12     -0.252      0.801   -2.12e-11    1.64e-11
X[12]       -2.41e-12   9.58e-12     -0.252      0.801   -2.12e-11    1.64e-11
X[13]      -2.467e-12   9.58e-12     -0.257      0.797   -2.13e-11    1.63e-11
X[14]      -2.467e-12   9.58e-12     -0.257      0.797   -2.13e-11    1.63e-11
X[15]      -2.467e-12   9.58e-12     -0.257      0.797   -2.13e-11    1.63e-11
X[16]      -2.467e-12   9.58e-12     -0.257      0.797   -2.13e-11    1.63e-11
X[17]      -2.467e-12   9.58e-12     -0.257      0.797   -2.13e-11    1.63e-11
X[18]       3.989e-11   2.33e-12     17.089      0.000    3.53e-11    4.45e-11
X[19]       2.134e-11   2.12e-12     10.082      0.000    1.72e-11    2.55e-11
X[20]       3.367e-11   2.14e-12     15.771      0.000    2.95e-11    3.79e-11
X[21]       2.802e-11   2.33e-12     12.002      0.000    2.34e-11    3.26e-11
X[22]       3.349e-11   1.98e-12     16.913      0.000    2.96e-11    3.74e-11
X[23]       2.949e-11   1.95e-12     15.143      0.000    2.57e-11    3.33e-11
X[24]       2.725e-11   1.97e-12     13.804      0.000    2.34e-11    3.11e-11
X[25]       3.092e-11   1.91e-12     16.167      0.000    2.72e-11    3.47e-11
X[26]       3.488e-11   1.98e-12     17.576      0.000     3.1e-11    3.88e-11
X[27]       2.673e-11   2.23e-12     11.975      0.000    2.24e-11    3.11e-11
X[28]       6.446e-11   2.13e-12     30.284      0.000    6.03e-11    6.86e-11
y              1.0000   9.03e-14   1.11e+13      0.000       1.000       1.000
==============================================================================
Omnibus:                       98.734   Durbin-Watson:                   0.016
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              376.122
Skew:                          -0.314   Prob(JB):                     2.12e-82
Kurtosis:                       5.678   Cond. No.                     6.24e+17
==

In [73]:
X_opt = X[:, [0, 3, 5]]
model = sm.ols(formula='y ~ X_opt + y', data=dataset)
results = model.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 5.334e+26
Date:                Tue, 01 Apr 2025   Prob (F-statistic):               0.00
Time:                        19:40:12   Log-Likelihood:                 28993.
No. Observations:                1193   AIC:                        -5.798e+04
Df Residuals:                    1191   BIC:                        -5.797e+04
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   8.788e-12   2.18e-11      0.403      0.687    -3.4e-11    5.16e-11
X_opt[0]   -2.558e-12   2.18e-11     -0.117      0.907   -4.54e-11    4.03e-11
X_opt[1]    1.226e-11   2.18e-11      0.562      0.574   -3.06e-11    5.51e-11
X_opt[2]    1.999e-11   2.18e-11      0.916      0.360   -2.28e-11    6.28e-11
y              1.0000   4.33e-14   2.31e+13      0.000       1.000       1.000
==============================================================================
Omnibus:                      721.039   Durbin-Watson:                   0.001
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             9715.363
Skew:                          -2.557   Prob(JB):                         0.00
Kurtosis:                      16.011   Cond. No.                     5.47e+35
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.62e-62. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [72]:
X_opt = X[:, [0, 3]]
model = sm.ols(formula='y ~ X_opt + y', data=dataset)
results = model.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 2.093e+25
Date:                Tue, 01 Apr 2025   Prob (F-statistic):               0.00
Time:                        19:40:07   Log-Likelihood:                 27061.
No. Observations:                1193   AIC:                        -5.412e+04
Df Residuals:                    1191   BIC:                        -5.411e+04
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   1.532e-11   1.47e-10      0.104      0.917   -2.73e-10    3.04e-10
X_opt[0]    2.982e-11   1.47e-10      0.203      0.839   -2.58e-10    3.18e-10
X_opt[1]   -5.084e-12   1.47e-10     -0.035      0.972   -2.93e-10    2.83e-10
y              1.0000   2.19e-13   4.58e+12      0.000       1.000       1.000
==============================================================================
Omnibus:                     1157.353   Durbin-Watson:                   0.000
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            69278.900
Skew:                          -4.423   Prob(JB):                         0.00
Kurtosis:                      39.269   Cond. No.                     6.25e+21
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.24e-34. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""